#!/usr/bin/env python3
from urllib import request, parse, error
from time import sleep
import math
import socket
import os
from common import general_m3u8_extractor, download_urls

# need update
title = "hello"
output_dir = "./video"

suffix = "ts"
need_merge = True
m3u8_url = r"https://youku163.zuida-bofang.com/20181225/22948_a81f138c/800k/hls/index.m3u8"
headers = {'user-agent':'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36'}
debug = False

def print_url(urls):
    for url in urls:
        print(url)

def start_work(**kwargs):
    urls = general_m3u8_extractor(m3u8_url, headers)
    if debug:
        print_url(urls)
        print("\nslice number of all TS is %d.\n" %len(urls))
    download_urls(urls, title, suffix, 0, output_dir = output_dir,
                  merge = need_merge, **kwargs)

if __name__ == '__main__':
    start_work()
